# config map is an api object used to store non-confidential data in key-value pairs.  Pods can consume ConfigMaps as environment variables, command-line arguments, or as configuration files in a volume.

apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
  labels:
    app: traefik
data:
  traefik.toml: |
    logLevel = "INFO"
    InsecureSkipVerify = true
    defaultEntryPoints = ["http","https"]
    
    # HTTP entrypoint
    [entryPoints]
    [entryPoints.http]
    address = ":80"
    compress = true
 
    # HTTPS entrypoint
   # [entryPoints.https]
   # address = ":443"
   # compress = true

   # [entryPoints.https.tls]
    #[[entryPoints.https.tls.certificates]]
    #CertFile = "/ssl/app.wlgore.com.crt"
    #KeyFile = "/ssl/app.wlgore.com.key"
 
  # API entrypoint for health monitoring and dashboard
   [entryPoints.api]
   address = ":8080"
 
  # Access logs
   [accessLog]
   format = "common"
 
    [api]
    entryPoint = "api"
    [kubernetes]
    ingressClass = "traefik"
    [traefikLog]
    format = "json"
    [ping]
    entryPoint = "api"
    