apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik  
    spec:
     serviceAccountName: traefik
     terminationGracePeriodSeconds: 60
     containers:
        - image: traefik:v1.7.24
          name: traefik
          volumeMounts:
           - mountPath: /config
             name: config
            #- mountPath: /ssl
            #  name: ssl
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
           # - name: api
           #  containerPort: 8080
          args:
             - --configfile=/config/traefik.toml         
     volumes:
        - name: config
          configMap:
           name: traefik    
        # - name: ssl
        #  secret:
        #    secretName: traefik-default-cert